config/routes.rb
Rails.application.routes.draw do
  resources :comment_likes
  get 'comments/new'
  get 'comments/create'
  resources :comments
  root 'microposts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :microposts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'microposts/new', to: 'microposts#new', as: 'microposts_new'
  get 'microposts/:id/edit', to: 'microposts#show', as: 'microposts_edit'

  get 'microposts/:id', to: 'microposts#show'
  get 'likes_new', to: 'likes#create'
  delete 'microposts/:id/likes', to: 'likes#destroy'

  get '/users/upvoted_submissions/:id', to: 'users#submissions'
  get '/users/upvoted_comments/:id', to: 'users#upvoted_comments'
  get 'users/:id/comments', to:'users#comments'

  get 'comment_likes_new', to: 'comment_likes#create'
  delete 'comments/:id/comment_likes', to: 'comment_likes#destroy'

  get '/threads', to: 'users#comments', as: 'user_comments'

  get '/comments/:id/replies', to: 'comments#reply'
  post '/comment_likes/:id', to: 'comment_likes#create'

  resources :microposts do
    resources :likes
  end

  resources :microposts do
    resources :comments
  end

  resources :comments do
    resources :comment_likes
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  has_many :comment_likes, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy like unlike]
  # GET /comments or /comments.json
  def index
    @comments = Comment.all
    micropost = params[:micropost]
    user = params[:user]
    if micropost != nil && user != nil
      render :json => { "status" => "400", "error" => "Do not fill both fields at the same time." }, status: :bad_request
    elsif micropost != nil
      if Micropost.where(id: micropost).exists?
        @comments = Comment.where(micropost_id: micropost).order(created_at: :desc)
      else
        render :json => { "status" => "404", "error" => "This micropost does not exist." }, status: :not_found and return
      end
    elsif user != nil
      if User.where(id: user).exists?
        @comments = Comment.where(user_id: user).order(created_at: :desc)
      else
        render :json => { "status" => "404", "error" => "This user does not exist." }, status: :not_found and return
      end
    end
  end
  # GET /comments/1 or /comments/1.json
  def show
    @comment = Comment.find(params[:id])
  end
  # GET /comments/new
  def new
    @comment = Comment.new
  end
  # GET /comments/1/edit
  def edit
  end
  # POST /comments or /comments.json
  def create
    api_key = request.headers[:HTTP_X_API_KEY]
    if api_key.nil?
      render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
    else
      @APIuser = User.find_by_api_key(api_key)
      current_user = @APIuser
      if @APIuser.nil?
        render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
      end
    end

    @micropost = Micropost.where(id: params[:micropost_id]).first
    if @micropost == nil
      render :json => { "status" => "404", "error" => "No Micropost found with the id provided." }, status: :not_found and return
    end
    if params[:parent_id] != nil
      parent = Comment.where(id: params[:parent_id]).first
      if parent == nil
        render :json => { "status" => "404", "error" => "No Parent Comment found with the id provided." }, status: :not_found and return
      end
    end
    @comment = @micropost.comments.new(comment_params)
    if current_user != nil
      @comment.user_id = current_user.id
      @comment.creator_name = current_user.email
    end

    respond_to do |format|
      if @comment.text != "" && @comment.save
        format.html { redirect_to  micropost_path(@micropost) }
        format.json { render :show, status: :created, location: micropost_path(@comment.micropost_id) }
      else
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    api_key = request.headers[:HTTP_X_API_KEY]
    if api_key.nil?
      render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
    else
      @APIuser = User.find_by_api_key(api_key)
      if @APIuser.nil?
        render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
      elsif @comment.user_id != @APIuser.id
        render :json => { "status" => "401", "error" => "Only the creator of the comment can edit it." }, status: :unauthorized and return
      end
    end
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to micropost_path(@comment.micropost_id)}
        format.json { render :show, status: :ok, location: micropost_path(@comment.micropost_id) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: comment.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /comments/1 or /comments/1.json
  def destroy
    api_key = request.headers[:HTTP_X_API_KEY]
    if api_key.nil?
      render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
    else
      @APIuser = User.find_by_api_key(api_key)
      if @APIuser.nil?
        render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
      elsif @comment.user_id != @APIuser.id
        render :json => { "status" => "401", "error" => "Only the creator of the comment can delete it." }, status: :unauthorized and return
      end
    end
    @comments = Comment.where(parent_id: @comment.id)
    @comments.each do |comment|
      comment.destroy
    end
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to user_comments_url }
        format.json { render :json => { "status" => "202", "Accepted" => "The comment has been deleted successfully." }, status: 202 and return }
      end
    end
  end
  def comment_like
    @comment.save
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
  def comment_unlike
    @comment.save
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
  def reply
    @comment = Comment.find(params[:id])
    @micropost = @comment.micropost_id
    respond_to do |format|
      format.html { render :showForm}
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end
  # Only allow a list of trusted parameters through.
  def comment_params
    if current_user != nil
      params.require(:comment).permit(:text, :user_id, :micropost_id, :parent_id)
    else
      params.permit(:text, :user_id, :micropost_id, :parent_id)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
 <div class="comment_info_list_comments">
      <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
            <% if current_user.email == User.search_name(comment.user_id)%>
              <span class="unable_unvote">*</span>
            <% elsif !pre_like%>
              <%= button_to '▲', comment_likes_path, params:{comment_id: comment.id}, method: :post, form_class:'upvoted_button', class: 'upvoted_button_c' %>
              <% else %>
              <span class="non-existent-vote"></span>
            <% end %>
          <% else %>
            <span class="upvote_comments"><a href="<%= new_user_session_path %>">▲</a></span>
          <% end %>
        <% end %>
      </span>
      <span> <%= comment.comment_likes.count %> <%= (comment.comment_likes.count) == 1 ? 'point' : 'points' %> by</span>
      <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% if current_user.email == User.search_name(comment.user_id.to_i)%>
              <a class="user" href="/users/edit"><%= User.search_name(comment.user_id.to_i) %></a>
            <% else %>
              <a class="user" href="/users/<%= comment.user_id.to_i %>"><%= User.search_name(comment.user_id.to_i) %></a>
            <% end %>
          <% else %>
              <a class="user" href="/users/<%= comment.user_id.to_i %>"><%= User.search_name(comment.user_id.to_i) %></a>
          <% end %>
        <% end %>
      </span>
      <span>
        <% if comment.created_at.to_i != 0 %>
          <% if ((Time.now - comment.created_at) / 1.year).round >= 1 %>
            <%= ((Time.now - comment.created_at) / 1.year).round %>  years ago
          <% else %>
            <% if ((Time.now - comment.created_at) / 1.month).round >= 1 %>
              <%= ((Time.now - comment.created_at) / 1.month).round %> months ago
            <% else %>
              <% if ((Time.now - comment.created_at) / 1.week).round >= 1 %>
                <%= ((Time.now - comment.created_at) / 1.week).round %> weeks ago
              <% else %>
                <% if ((Time.now - comment.created_at) / 1.day).round >= 1 %>
                  <%= ((Time.now - comment.created_at) / 1.day).round %>  days ago
                <% else %>
                  <% if ((Time.now - comment.created_at) / 1.hour).round >= 1 %>
                    <%= ((Time.now - comment.created_at) / 1.hour).round %> hours ago
                  <% else %>
                    <% if ((Time.now - comment.created_at) / 1.minute).round >= 1 %>
                      <%= ((Time.now - comment.created_at) / 1.minute).round %> minutes ago
                    <% else %>
                      <%= ((Time.now - comment.created_at) / 1.second).round %> seconds ago
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </span>
   <span class = "barres">
      |
   </span>
      <span>
        <a href="<%= micropost_path(comment.micropost_id) %>">
          <span class="edit">parent</span>
        </a>
      </span>
      <span>
        <% if current_user %>
          <% if current_user.id == comment.user_id %>
            <span class = "barres">
              |
            </span>
            <a class="edit" href="<%="/comments/"%><%=comment.id%><%="/edit"%>"><%= "edit" %></a>
          <% end %>
        <% end %>
      </span>
       <span>
        <% if current_user %>
        <% if current_user.id == comment.user_id%>
             <span class = "barres">
               |
             </span>
           <%= button_to 'delete', comment, method: :delete, form_class: 'delete_button', class: 'delete'%>
        <% end %>
      <% end %>
      </span>
      <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
              <% if pre_like %>
                <span class = "barres">|</span>
              <%= button_to 'unvote', comment_like_path(pre_like), params:{comment_id: comment.id} ,method: :delete, form_class:'downvoted_button', class: 'delete' %>
              <% end %>
          <% end %>
       <%end%>
      </span>
  <p class="comment_text" style="margin-top:2px;margin-right: 10px;margin-bottom:1px">
    <%= comment.text %>
  </p>
  <a href="/comments/<%=comment.id%>/replies" class="comment-form-display">reply</a>
  <br><br>
  <div class="sub-comment">
    <%= render comment.comments.order(id: :desc) %>
  </div> 
 </div>

app/views/comments/_editForm.html.erb
<%= form_with(model: comment) do |editForm| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="taula_edit_comment">
    <tbody>
    <tr>
      <td class=taula_submit valign = "top">
        <%= editForm.label :text %>:
      </td>
      <td><%= editForm.text_area :text, :size => "60x5"%></td>
    </tr>
    <br>
    <tr>
      <td>
        <br>
        <%= editForm.submit "update" %>
      </td>
    </tr>
    </tbody>
  </table>

<% end %>

app/views/comments/_form.html.erb
<%= form_for(micropost.comments.build, url: "/microposts/#{micropost.id}/comments") do |f| %>
  <% unless parent.nil? %>
<input type="hidden" name="comment[parent_id]" value="<%=  parent  %>">
<%  end %>
  <%= f.hidden_field :micropost_id %>

  <p style="padding-left: 25px">
    <%= f.text_area :text, :size => "80x8" %>
  </p>
  <p style="padding-left: 25px">
    <% if current_user %>
      <%= f.submit "reply"%>
    <% else %>
      <button id="mybutton"><a href="<%= new_user_session_path %>">add comment</a></button>
    <% end %>
  </p>
<%end%>

app/views/comments/edit.html.erb
<thead>
  <table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
    <tr>
      <td bgcolor="#ff6600">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
          <tbody>
          <tr>
            <td style="width:18px;padding-right:4px">
              <a href=<% microposts_url %>>
                <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
              </a>
            </td>
            <td style="line-height:12pt; height:10px;">
              <span class="pagetop"><b class="=hname"><%= link_to 'Hacker News', microposts_url, class: 'ruby_link' %></b></span>
              <span class="pagetop_new"><%= link_to 'new', microposts_url(:sort => "date"), class: 'ruby_link' %></span>
              <% if current_user %>
                | <span class="pagetop"><a href="/users/<%= current_user.id %>/comments"> threads </a> </span>
              <% end %>
              | <span class="pagetop"><%= link_to 'ask', microposts_url(:type =>"ask"), class: 'ruby_link' %></span>
              <% if current_user %>
                | <span class="pagetop"><%= link_to 'submit', new_micropost_url, class: 'ruby_link' %></span>
              <% else %>
                | <span class="pagetop"><%= link_to 'submit', new_user_session_path, class: 'ruby_link' %></span>
              <% end %>
            </td>
            <td style="text-align:right;padding-right:4px;">
              <%= link_to current_user.email, edit_user_registration_path, class: 'ruby_link' %>
              | <%= link_to 'logout', destroy_user_session_path, class: 'ruby_link', data: { turbo: "false" }, method: :delete %>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr style="height:10px"></tr>
  </table>
</thead>

<table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
  <tr>
    <td class="comment_info_list_comments">
      <span>
        <span class="unable_unvote">*</span>
      </span>
      <span> <%= @comment.comment_likes.count %> <%= (@comment.comment_likes.count) == 1 ? 'point' : 'points' %> by</span>
      <span>
        <% if @comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% if current_user.email == User.search_name(@comment.user_id.to_i)%>
              <a class="link_user" href="/users/edit"><%= User.search_name(@comment.user_id.to_i) %></a>
            <% else %>
              <a class="link_user" href="/users/<%= User.search_name(@comment.user_id.to_i) %>"><%= User.search_name(@comment.user_id.to_i) %></a>
            <% end %>
          <% else %>
              <a class="link_user" href="/users/<%= User.search_name(@comment.user_id.to_i) %>"><%= User.search_name(@comment.user_id.to_i) %></a>
          <% end %>
        <% end %>
      </span>
      <span>
        <% if @comment.created_at.to_i != 0 %>
          <% if ((Time.now - @comment.created_at) / 1.year).round >= 1 %>
            <%= ((Time.now - @comment.created_at) / 1.year).round %>  years ago
          <% else %>
            <% if ((Time.now - @comment.created_at) / 1.month).round >= 1 %>
              <%= ((Time.now - @comment.created_at) / 1.month).round %> months ago
            <% else %>
              <% if ((Time.now - @comment.created_at) / 1.week).round >= 1 %>
                <%= ((Time.now - @comment.created_at) / 1.week).round %> weeks ago
              <% else %>
                <% if ((Time.now - @comment.created_at) / 1.day).round >= 1 %>
                  <%= ((Time.now - @comment.created_at) / 1.day).round %>  days ago
                <% else %>
                  <% if ((Time.now - @comment.created_at) / 1.hour).round >= 1 %>
                    <%= ((Time.now - @comment.created_at) / 1.hour).round %> hours ago
                  <% else %>
                    <% if ((Time.now - @comment.created_at) / 1.minute).round >= 1 %>
                      <%= ((Time.now - @comment.created_at) / 1.minute).round %> minutes ago
                    <% else %>
                      <%= ((Time.now - @comment.created_at) / 1.second).round %> seconds ago
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </span>
      <span>
        <a href="<%= micropost_path(@comment.micropost_id) %>">
          <span class="comments"> | parent</span>
        </a>
      </span>
      <p class="comment_text" style="margin-top:2px;margin-right: 10px">
        <%= @comment.text %>
      </p>
    </td>
  </tr>
  </tbody>

  <tbody class="itemlist">
    <tr height="20px">
      <td class="taula_sencera">
        <%= render "editForm", comment: @comment %>
      </td>
    </tr>
    <tr><td><br></td></tr>
  </tbody>
</table>
<br>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <table>
    <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Submission</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <%= render comment %>
      <tr>
        <td><%= comment.text %>></td>
        <td><%= comment.user_id %>></td>
        <td><%= comment.micropost_id%></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure you want to delete this comment? This action is irreversible'} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<thead>
<table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tr>
    <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=<% microposts_url %>>
              <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="=hname"><%= link_to 'Add Comment', microposts_url, class: 'ruby_link' %></b></span>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  <tr style="height:10px"></tr>
</table>
</thead>

<table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">

  <tbody class="itemlist">
    <tr>
      <td>
        <%= render @comment %>
      </td>
    </tr>
    <tr>
      <td class="taula_sencera">
        <%= form_for([@comment, @comment.replies.build]) do |f| %>
          <p style="padding-left: 25px">
            <%= f.text_area :text, :size => "80x8" %>
          </p>
          <p style="padding-left: 25px">
            <% if current_user %>
              <%= f.submit "reply"%>
            <% else %>
              <button id="mybutton"><a href="<%= new_user_session_path %>">reply</a></button>
            <% end %>
          </p>
        <%end%>
      </td>
    </tr>
  </tbody>
</table>

app/views/comments/showForm.html.erb
<thead>
<table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tr>
    <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=<% microposts_url %>>
              <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="=hname"><%= link_to 'Add Comment', microposts_url, class: 'ruby_link' %></b></span>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  <tr style="height:10px"></tr>
</table>
</thead>

<table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">

  <tbody class="itemlist">
  <tr>
    <td>
      <span>
        <% if @comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = @comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
            <% if current_user.email == User.search_name(@comment.user_id)%>
              <span class="unable_unvote">*</span>
            <% elsif !pre_like%>
              <%= button_to '▲', comment_likes_path, params:{comment_id: @comment.id}, method: :post, form_class:'upvoted_button', class: 'upvoted_button_c' %>
            <% else %>
              <span class="non-existent-vote"></span>
            <% end %>
          <% else %>
            <span class="upvote_comments"><a href="<%= new_user_session_path %>">▲</a></span>
          <% end %>
        <% end %>
      </span>
      <span class="hora"> <%= @comment.comment_likes.count %> <%= (@comment.comment_likes.count) == 1 ? 'point' : 'points' %> by</span>
      <span>
        <% if @comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% if current_user.email == User.search_name(@comment.user_id.to_i)%>
              <a class="user" href="/users/edit"><%= User.search_name(@comment.user_id.to_i) %></a>
            <% else %>
              <a class="user" href="/users/<%= @comment.user_id.to_i %>"><%= User.search_name(@comment.user_id.to_i) %></a>
            <% end %>
          <% else %>
              <a class="user" href="/users/<%= @comment.user_id.to_i %>"><%= User.search_name(@comment.user_id.to_i) %></a>
          <% end %>
        <% end %>
      </span>
      <span class = "comment_info_list_comments">
        <% if @comment.created_at.to_i != 0 %>
          <% if ((Time.now - @comment.created_at) / 1.year).round >= 1 %>
            <%= ((Time.now - @comment.created_at) / 1.year).round %>  years ago
          <% else %>
            <% if ((Time.now - @comment.created_at) / 1.month).round >= 1 %>
              <%= ((Time.now - @comment.created_at) / 1.month).round %> months ago
            <% else %>
              <% if ((Time.now - @comment.created_at) / 1.week).round >= 1 %>
                <%= ((Time.now - @comment.created_at) / 1.week).round %> weeks ago
              <% else %>
                <% if ((Time.now - @comment.created_at) / 1.day).round >= 1 %>
                  <%= ((Time.now - @comment.created_at) / 1.day).round %>  days ago
                <% else %>
                  <% if ((Time.now - @comment.created_at) / 1.hour).round >= 1 %>
                    <%= ((Time.now - @comment.created_at) / 1.hour).round %> hours ago
                  <% else %>
                    <% if ((Time.now - @comment.created_at) / 1.minute).round >= 1 %>
                      <%= ((Time.now - @comment.created_at) / 1.minute).round %> minutes ago
                    <% else %>
                      <%= ((Time.now - @comment.created_at) / 1.second).round %> seconds ago
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </span>
      <span>
        <span class="barres">|</span>
        <a href="<%= micropost_path(@comment.micropost_id) %>">
          <span class="edit">parent</span>
        </a>
      </span>
      <span>
        <% if current_user %>
          <% if current_user.id == @comment.user_id %>
            <span class="barres">|</span>
            <a class="edit" href="<%="/comments/"%><%=@comment.id%><%="/edit"%>"><%= "edit" %></a>
          <% end %>
        <% end %>
      </span>
      <span>
        <% if @comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = @comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
            <% if pre_like %>
                <span class = "barres">|</span>
              <%= button_to 'unvote', comment_like_path(pre_like), params:{comment_id: @comment.id} ,method: :delete, form_class:'downvoted_button', class: 'delete' %>
              <% end %>
          <% end %>
       <%end%>
      </span>
      <p class="comment_text" style="margin-top:2px;margin-right: 10px">
        <%= @comment.text %>
      </p>
    </td>
  </tr>
  <tr>
    <td class="taula_sencera">
      <div class="comment-form">
        <%= render partial: 'comments/form', locals: {micropost: @comment.micropost, parent: @comment.id} %>
      </div>
    </td>
  </tr>
  </tbody>
</table>