config/routes.rb
Rails.application.routes.draw do
  resources :comment_likes
  get 'comments/new'
  get 'comments/create'
  resources :comments
  root 'microposts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :microposts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'microposts/new', to: 'microposts#new', as: 'microposts_new'
  get 'microposts/:id/edit', to: 'microposts#show', as: 'microposts_edit'

  get 'microposts/:id', to: 'microposts#show'
  get 'likes_new', to: 'likes#create'
  delete 'microposts/:id/likes', to: 'likes#destroy'

  get '/users/upvoted_submissions/:id', to: 'users#submissions'
  get '/users/upvoted_comments/:id', to: 'users#upvoted_comments'
  get 'users/:id/comments', to:'users#comments'

  get 'comment_likes_new', to: 'comment_likes#create'
  delete 'comments/:id/comment_likes', to: 'comment_likes#destroy'

  get '/threads', to: 'users#comments', as: 'user_comments'

  get '/comments/:id/replies', to: 'comments#reply'
  post '/comment_likes/:id', to: 'comment_likes#create'

  resources :microposts do
    resources :likes
  end

  resources :microposts do
    resources :comments
  end

  resources :comments do
    resources :comment_likes
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  before_create :set_api_key
  has_many :microposts
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :comment_likes, dependent: :destroy
  has_many :replies, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name   # assuming the user model has a name
      user.avatar_url = auth.info.image # assuming the user model has an image
    end
  end

  def self.search_name(id)
    @user = User.find(id)
    if @user.name != nil
      return @user.name
    else
      return @user.email
    end
  end

  def generate_api_key
    SecureRandom.base58(24)
  end

  def set_api_key
    self.api_key = generate_api_key
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def google_oauth2
    user = User.from_omniauth(auth)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  private

  def auth
    @auth ||= request.env['omniauth.auth']
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def update_resource(resource, params)
    if resource.provider == 'google_oauth2'
      params.delete('current_password')
      resource.password = params['password']
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  # GET /users or /users.json
  def index
    @users = User.all
  end
  # GET /users/1 or /users/1.json
  def show
    @user = User.find_by_id(params[:id])
  end
  # GET /users/new
  def new
    @user = User.new
  end
  # GET /users/1/edit
  def edit
  end
  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /users/1 or /users/1.json
  def update
    api_key = request.headers[:HTTP_X_API_KEY]
    if api_key.nil?
      render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
    else
      @APIuser = User.find_by_api_key(api_key)
      if @APIuser.nil?
        render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
      elsif @APIuser.id != @user.id
        render :json => { "status" => "401", "error" => "Only the user can edit his biography." }, status: :unauthorized and return
      end
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to '/users/edit' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /users/1 or /users/1.json
  def destroy
    params[:id] = nil
    redirect_to root_path
=begin
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
=end
  end
  def submissions
    api_key = request.headers[:HTTP_X_API_KEY]
    if api_key.nil?
      if current_user
        @likes = Like.where(user_id: current_user.id)
      else
        render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
      end
    else
      @user = User.find_by_api_key(api_key)
      if @user.id.to_s === params[:id].to_s
        @likes = Like.where(user_id: @user.id)
      else
        render :json => { "status" => "401", "error" => "Only the owner can view its liked microposts." }, status: :unauthorized and return
      end
    end
    @microposts = []
    for like in @likes
      @microposts << Micropost.find_by_id(like.micropost_id)
    end
    respond_to do |format|
      format.html { render :user_submissions}
      format.json { render :json => @microposts, status: :created }
    end
  end
  def upvoted_comments
    api_key = request.headers[:HTTP_X_API_KEY]
    if current_user.nil?
      if api_key.nil?
        render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
      else
        @user = User.find_by_api_key(api_key)
        if @user.nil?
          render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
        elsif params[:id].to_s != @user.id.to_s
          render :json => { "status" => "401", "error" => "Only the owner can view its liked comments." }, status: :unauthorized and return
        end
      end
    else
      @user = current_user
    end

    @comment_likes = CommentLike.where(user_id: @user.id)
    @comment_likes.each do |like|
      print(like.id)
    end
    respond_to do |format|
      format.html { render :user_upvoted_comments}
      format.json { render :json => @comment_likes, status: :created }
    end
  end
  def comments
    @user = User.find(params[:id])
    @comments = Comment.where(user_id: @user.id).order(likes_count: :desc)
    respond_to do |format|
      format.html { render :user_comments}
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    if params[:id] == "sign_out"
      sign_out current_user
    elsif User.where(id: params[:id]).exists?
      @user = User.find(params[:id])
    else
      render :json => { "status" => "404", "error" => "The user with the id provided doesn't exist" }, status: :not_found and return
    end
  end
  # Only allow a list of trusted parameters through.
  def user_params
    if current_user != nil
      params.require(:user).permit(:name, :email, :about)
    else
      params.permit(:name, :email, :about)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @user != nil %>
  <%= render @user %>
<% else %>
  <%= controller.redirect_to root_path %>
<% end %>

app/views/users/user_comments.html.erb
<thead>
<table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tr>
    <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" >
        <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=<% microposts_url %>>
              <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="=hname"><%= link_to 'Hacker News', microposts_url, class: 'ruby_link' %></b></span>
            <span class="pagetop_new"><%= link_to 'new', microposts_url(:sort =>"date"), class: 'ruby_link' %></span>
            <% if current_user %>
              <span class="pagetop"><a href="/users/<%= current_user.id %>/comments"> | threads </a> </span>
            <% end %>
            | <span class="pagetop"><%= link_to 'ask', microposts_url(:type =>"ask"), class: 'ruby_link' %></span>
            <% if current_user %>
              | <span class="pagetop"><%= link_to 'submit', new_micropost_url, class: 'ruby_link' %></span>
            <% else %>
              | <span class="pagetop"><%= link_to 'submit', new_user_session_path, class: 'ruby_link' %></span>
            <% end %>
          </td>
          <td style="text-align:right;padding-right:4px;">
            <% if current_user %>
              <%= link_to current_user.email, edit_user_registration_path, class: 'ruby_link' %>
              | <%= link_to 'logout', destroy_user_session_path, class: 'ruby_link', data: {turbo: "false"}, method: :delete %>
            <% else %>
              <%= link_to 'login', new_user_session_path, class: 'ruby_link' %>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
</table>

<tbody border="0" cellpadding="0" cellspacing="0" class="itemlist">

<% i = 0 %>
<% @comments.each do |comment| %>
  <% micropost = Micropost.where(id: comment.user_id ) %>
  <% i = i + 1 %>
  <table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
    <% if i == 1 %>
      <tr><td><br class="br_ini_upvoted_list"></td></tr>
    <% end %>
    <tr>
      <td class="non_existent_point"><span>.</span></td>
      <td class="sub">
        <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
              <% if current_user.email == User.search_name(comment.user_id)%>
              <span class="unable_unvote">*</span>
            <% elsif !pre_like%>
              <%= button_to '▲', comment_likes_path, params:{comment_id: comment.id}, method: :post, form_class:'upvoted_button', class: 'upvoted_button_c' %>
              <% else %>
              <span class="non-existent-vote"></span>
            <% end %>
          <% else %>
            <span class="upvote_comments"><a href="<%= new_user_session_path %>">▲</a></span>
          <% end %>
        <% end %>
      </span>
        <span class = "edit"> <%= comment.comment_likes.count %> <%= (comment.comment_likes.count) == 1 ? 'point' : 'points' %> by</span>
        <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% if current_user.email == User.search_name(comment.user_id.to_i)%>
              <a class="user" href="/users/edit"><%= User.search_name(comment.user_id.to_i) %></a>
            <% else %>
              <a class="user" href="/users/<%= comment.user_id.to_i %>"><%= User.search_name(comment.user_id.to_i) %></a>
            <% end %>
          <% else %>
              <a class="user" href="/users/<%= comment.user_id.to_i %>"><%= User.search_name(comment.user_id.to_i) %></a>
          <% end %>
        <% end %>
      </span>
        <span class = "hora">
        <% if comment.created_at.to_i != 0 %>
          <% if ((Time.now - comment.created_at) / 1.year).round >= 1 %>
            <%= ((Time.now - comment.created_at) / 1.year).round %>  years ago
          <% else %>
            <% if ((Time.now - comment.created_at) / 1.month).round >= 1 %>
              <%= ((Time.now - comment.created_at) / 1.month).round %> months ago
            <% else %>
              <% if ((Time.now - comment.created_at) / 1.week).round >= 1 %>
                <%= ((Time.now - comment.created_at) / 1.week).round %> weeks ago
              <% else %>
                <% if ((Time.now - comment.created_at) / 1.day).round >= 1 %>
                  <%= ((Time.now - comment.created_at) / 1.day).round %>  days ago
                <% else %>
                  <% if ((Time.now - comment.created_at) / 1.hour).round >= 1 %>
                    <%= ((Time.now - comment.created_at) / 1.hour).round %> hours ago
                  <% else %>
                    <% if ((Time.now - comment.created_at) / 1.minute).round >= 1 %>
                      <%= ((Time.now - comment.created_at) / 1.minute).round %> minutes ago
                    <% else %>
                      <%= ((Time.now - comment.created_at) / 1.second).round %> seconds ago
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </span>
        <span class="barres">|</span>
        <span>
        <a href="<%= micropost_path(comment.micropost_id) %>">
          <span class="edit">parent</span>
        </a>
      </span>
        <span>
        <% if current_user %>
          <% if current_user.id == comment.user_id %>
              <span class="barres">
                |
              </span>
            <a class="edit" href="<%="/comments/"%><%=comment.id%><%="/edit"%>"><%= "edit" %></a>
          <% end %>
        <% end %>
      </span>

        <span>
        <% if current_user %>
        <% if current_user.id == comment.user_id%>
              <span class="barres">
                |
              </span>
              <%= button_to 'delete', comment, method: :delete, form_class: 'delete_button', class: 'delete'%>
        <% end %>
      <% end %>
      </span>
        <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
              <% if pre_like %>
                <span class="barres">
                  |
                </span>
                <%= button_to 'unvote', comment_like_path(pre_like), params:{comment_id: comment.id} ,method: :delete, form_class:'downvoted_button', class: 'downvoted_button_c' %>
              <% end %>
          <% end %>
       <%end%>
      </span>
        <p class="comment_text" style="margin-top:2px;margin-right: 10px;margin-bottom:1px">
          <%= comment.text %>
        </p>
        <a href="/comments/<%=comment.id%>/replies" class="comment-form-display">reply</a>
      </td>
    </tr>
    <tr>
      <td>
        <br class="br_between_comments">
      </td>
    </tr>
    <% if i == @comments.size %>
      <tr>
        <td>
          <br class="br_peu">
        </td>
      </tr>
    <% end %>
  </table>
<%end%>

app/views/users/user_upvoted_comments.erb
<thead>
<table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tr>
    <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" >
        <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=<% microposts_url %>>
              <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="=hname"><%= link_to 'Hacker News', microposts_url, class: 'ruby_link' %></b></span>
            <span class="pagetop_new"><%= link_to 'new', microposts_url(:sort =>"date"), class: 'ruby_link' %></span>
            <% if current_user %>
              <span class="pagetop"><a href="/users/<%= current_user.id %>/comments"> | threads </a> </span>
            <% end %>
            | <span class="pagetop"><%= link_to 'ask', microposts_url(:type =>"ask"), class: 'ruby_link' %></span>
            <% if current_user %>
              | <span class="pagetop"><%= link_to 'submit', new_micropost_url, class: 'ruby_link' %></span>
            <% else %>
              | <span class="pagetop"><%= link_to 'submit', new_user_session_path, class: 'ruby_link' %></span>
            <% end %>
            | <span class="pagetop_upvoted">upvoted comments</span>
          </td>
          <td style="text-align:right;padding-right:4px;">
            <% if current_user %>
              <%= link_to current_user.email, edit_user_registration_path, class: 'ruby_link' %>
              | <%= link_to 'logout', destroy_user_session_path, class: 'ruby_link', data: {turbo: "false"}, method: :delete %>
            <% else %>
              <%= link_to 'login', new_user_session_path, class: 'ruby_link' %>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  <tr style="height:10px"></tr>
</table>

<tbody border="0" cellpadding="0" cellspacing="0" class="itemlist">

<% i = 0 %>
<% @comment_likes.each do |comment_like| %>
  <% comment = Comment.find_by(id: comment_like.comment_id ) %>
  <% i = i + 1 %>
  <table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
    <% if i == 1 %>
      <tr><td><br class="br_ini_upvoted_list"></td></tr>
    <% end %>
    <tr class="comment_info_list_comments">
      <td class="enum"><span><%= i %>.</span></td>
      <td class="sub">
              <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
                    <% if current_user.email == User.search_name(comment.user_id)%>
              <span class="unable_unvote">*</span>
            <% elsif !pre_like%>
              <%= button_to '▲', comment_likes_path, params:{comment_id: comment.id}, method: :post, form_class:'upvoted_button', class: 'upvoted_button_c' %>
              <% else %>
              <span class="non-existent-vote"></span>
            <% end %>
          <% else %>
            <span class="upvote"><a href="<%= new_user_session_path %>">▲</a></span>
          <% end %>
        <% end %>
      </span>
        <span> <%= comment.comment_likes.count %> <%= (comment.comment_likes.count) == 1 ? 'point' : 'points' %> by</span>
        <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% if current_user.email == User.search_name(comment.user_id.to_i)%>
              <a class="link_user" href="/users/edit"><%= User.search_name(comment.user_id.to_i) %></a>
            <% else %>
              <a class="link_user" href="/users/<%= comment.user_id.to_i %>"><%= User.search_name(comment.user_id.to_i) %></a>
            <% end %>
          <% else %>
              <a class="link_user" href="/users/<%= comment.user_id.to_i %>"><%= User.search_name(comment.user_id.to_i) %></a>
          <% end %>
        <% end %>
      </span>
        <span>
        <% if comment.created_at.to_i != 0 %>
          <% if ((Time.now - comment.created_at) / 1.year).round >= 1 %>
            <%= ((Time.now - comment.created_at) / 1.year).round %>  years ago
          <% else %>
            <% if ((Time.now - comment.created_at) / 1.month).round >= 1 %>
              <%= ((Time.now - comment.created_at) / 1.month).round %> months ago
            <% else %>
              <% if ((Time.now - comment.created_at) / 1.week).round >= 1 %>
                <%= ((Time.now - comment.created_at) / 1.week).round %> weeks ago
              <% else %>
                <% if ((Time.now - comment.created_at) / 1.day).round >= 1 %>
                  <%= ((Time.now - comment.created_at) / 1.day).round %>  days ago
                <% else %>
                  <% if ((Time.now - comment.created_at) / 1.hour).round >= 1 %>
                    <%= ((Time.now - comment.created_at) / 1.hour).round %> hours ago
                  <% else %>
                    <% if ((Time.now - comment.created_at) / 1.minute).round >= 1 %>
                      <%= ((Time.now - comment.created_at) / 1.minute).round %> minutes ago
                    <% else %>
                      <%= ((Time.now - comment.created_at) / 1.second).round %> seconds ago
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </span>
        <span class="barres">|</span>
        <span>
        <a href="<%= micropost_path(comment.micropost_id) %>">
          <span class="edit">parent</span>
        </a>
      </span>
        <span>
        <% if comment.user_id.to_i != 0 %>
          <% if current_user %>
            <% pre_like = comment.comment_likes.find { |comment_like| comment_like.user_id == current_user.id} %>
              <% if pre_like %>
                | <%= button_to 'unvote', comment_like_path(pre_like), params:{comment_id: comment.id} ,method: :delete, form_class:'downvoted_button', class: 'delete' %>
              <% end %>
          <% end %>
       <%end%>
      </span>
        <p class="comment_text" style="margin-top:2px;margin-right: 10px;margin-bottom:1px">
          <%= comment.text %>
        </p>
        <a href="/comments/<%=comment.id%>/replies" class="comment-form-display">reply</a>
        <br><br>
      </td>
    </tr>
    <tr>
      <td>
        <br class="br_between_comments_likes">
      </td>
    </tr>
    <% if i == @comment_likes.size %>
      <tr>
        <td>
          <br class="br_peu">
        </td>
        <td>
          <hr class="orange_line">
          <br>
        </td>
      </tr>
    <% end %>
  </table>
<%end%>