config/routes.rb
Rails.application.routes.draw do
  resources :comment_likes
  get 'comments/new'
  get 'comments/create'
  resources :comments
  root 'microposts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :microposts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'microposts/new', to: 'microposts#new', as: 'microposts_new'
  get 'microposts/:id/edit', to: 'microposts#show', as: 'microposts_edit'

  get 'microposts/:id', to: 'microposts#show'
  get 'likes_new', to: 'likes#create'
  delete 'microposts/:id/likes', to: 'likes#destroy'

  get '/users/upvoted_submissions/:id', to: 'users#submissions'
  get '/users/upvoted_comments/:id', to: 'users#upvoted_comments'
  get 'users/:id/comments', to:'users#comments'

  get 'comment_likes_new', to: 'comment_likes#create'
  delete 'comments/:id/comment_likes', to: 'comment_likes#destroy'

  get '/threads', to: 'users#comments', as: 'user_comments'

  get '/comments/:id/replies', to: 'comments#reply'
  post '/comment_likes/:id', to: 'comment_likes#create'

  resources :microposts do
    resources :likes
  end

  resources :microposts do
    resources :comments
  end

  resources :comments do
    resources :comment_likes
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/controllers/comment_likes_controller.rb
class CommentLikesController < ApplicationController
  before_action :find_comment_like, only: [:destroy]
  # POST /comment_likes or /comment_likes.json
  def create
    @comment = Comment.where(id: params[:id]).first
    if @comment == nil
      render :json => { "status" => "401", "error" => "Comment not found." }, status: :not_found and return
    end
    api_key = request.headers[:HTTP_X_API_KEY]
    if api_key.nil?
      render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
    else
      @APIuser = User.find_by_api_key(api_key)
      if @APIuser.nil?
        render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
      elsif @comment.user_id == @APIuser.id
        render :json => { "status" => "401", "error" => "The creator of the comment can't like it." }, status: :unauthorized and return
      end
    end
    if already_liked_vote?(@comment.id)
      render :json => { "status" => "401", "error" => "Can't like the same comment." }, status: :unauthorized
    else
      if current_user.nil?
        current_user = @APIuser
      end
      @comment.comment_likes.create(user_id: current_user.id)
      @comment.likes_count+=1
      @comment.save
      respond_to do |format|
        format.json { render :json => { "status" => "202", "Accepted" => "The comment has been voted successfully." }, status: 202 and return }
      end
    end
  end
  # DELETE /comment_likes/1 or /comment_likes/1.json
  def destroy
    @comment = Comment.where(id: params[:id]).first
    if @comment == nil
      render :json => { "status" => "404", "error" => "Comment not found." }, status: :not_found and return
    end
    api_key = request.headers[:HTTP_X_API_KEY]
    if api_key.nil?
      render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
    else
      @APIuser = User.find_by_api_key(api_key)
      if @APIuser.nil?
        render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
      elsif @comment.user_id == @APIuser.id
        render :json => { "status" => "401", "error" => "The creator of the comment can't unlike it." }, status: :unauthorized and return
      end
    end
    if already_liked_unvote?(@comment.id)
      @comment.likes_count-=1
      @comment_like.destroy
      @comment.save
      respond_to do |format|
        format.json { render :json => { "status" => "202", "Accepted" => "The comment has been unvoted successfully." }, status: 202 and return }
      end
      if current_user != nil
        redirect_back fallback_location: root_path # redirect_to microposts_path(@micropost)
      end
    else
      render :json => { "status" => "401", "error" => "Can't unlike a comment that didn't like before o already had unliked" }, status: :bad_request
    end
  end
  def find_comment_like
    @comment_like = CommentLike.where(comment_id: params[:id]).first
  end
  private
  def already_liked_vote?(id)
    api_key = request.headers[:HTTP_X_API_KEY]
    @user = User.find_by_api_key(api_key)
    CommentLike.where(user_id: @user.id, comment_id: id).exists?
  end
  # Use callbacks to share common setup or constraints between actions.
  def already_liked_unvote?(id)
    api_key = request.headers[:HTTP_X_API_KEY]
    @user = User.find_by_api_key(api_key)
    CommentLike.where(user_id: @user.id, comment_id: id).exists?
  end
  def find_comment
    @comment = Comment.find_by(id: params[:comment_id])
  end
end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
end

app/views/comment_likes/_comment_like.html.erb
<div id="<%= dom_id comment_like %>">
  <p>
    <strong>Comment:</strong>
    <%= comment_like.comment_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment_like.user_id %>
  </p>

</div>

app/views/comment_likes/_form.html.erb
<%= form_with(model: comment_like) do |form| %>
  <% if comment_like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment_like.errors.count, "error") %> prohibited this comment_like from being saved:</h2>

      <ul>
        <% comment_like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :comment_id, style: "display: block" %>
    <%= form.text_field :comment_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comment_likes/edit.html.erb
<h1>Editing comment like</h1>

<%= render "form", comment_like: @comment_like %>

<br>

<div>
  <%= link_to "Show this comment like", @comment_like %> |
  <%= link_to "Back to comment likes", comment_likes_path %>
</div>

app/views/comment_likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comment likes</h1>

<div id="comment_likes">
  <% @comment_likes.each do |comment_like| %>
    <%= render comment_like %>
    <p>
      <%= link_to "Show this comment like", comment_like %>
    </p>
  <% end %>
</div>

<%= link_to "New comment like", new_comment_like_path %>

app/views/comment_likes/new.html.erb
<h1>New comment like</h1>

<%= render "form", comment_like: @comment_like %>

<br>

<div>
  <%= link_to "Back to comment likes", comment_likes_path %>
</div>

app/views/comment_likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment_like %>

<div>
  <%= link_to "Edit this comment like", edit_comment_like_path(@comment_like) %> |
  <%= link_to "Back to comment likes", comment_likes_path %>

  <%= button_to "Destroy this comment like", @comment_like, method: :delete %>
</div>