config/routes.rb
Rails.application.routes.draw do
  resources :comment_likes
  get 'comments/new'
  get 'comments/create'
  resources :comments
  root 'microposts#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :microposts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'microposts/new', to: 'microposts#new', as: 'microposts_new'
  get 'microposts/:id/edit', to: 'microposts#show', as: 'microposts_edit'

  get 'microposts/:id', to: 'microposts#show'
  get 'likes_new', to: 'likes#create'
  delete 'microposts/:id/likes', to: 'likes#destroy'

  get '/users/upvoted_submissions/:id', to: 'users#submissions'
  get '/users/upvoted_comments/:id', to: 'users#upvoted_comments'
  get 'users/:id/comments', to:'users#comments'

  get 'comment_likes_new', to: 'comment_likes#create'
  delete 'comments/:id/comment_likes', to: 'comment_likes#destroy'

  get '/threads', to: 'users#comments', as: 'user_comments'

  get '/comments/:id/replies', to: 'comments#reply'
  post '/comment_likes/:id', to: 'comment_likes#create'

  resources :microposts do
    resources :likes
  end

  resources :microposts do
    resources :comments
  end

  resources :comments do
    resources :comment_likes
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
  validate :isThereAnyUrlOrText

  def isThereAnyUrlOrText
    if (url.blank? and text.blank?)
      errors[:base] << "A text or a url needs to be provided"
    elsif not (url.blank? ^text.blank?)
      errors[:base] << "A text or a url needs to be provided, not both"
    end

  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy like unlike]

  # GET /microposts or /microposts.json
  def index
    # api_key = request.headers[:HTTP_X_API_KEY]
    @microposts = Micropost.order(likes_count: :desc)

    sort = params[:sort]
    type = params[:type]
    user = params[:user]

    if sort == 'date'
      @microposts = Micropost.order(created_at: :desc)
    elsif type == 'ask'
      @microposts = Micropost.where(url: [nil, ""]).order(likes_count: :desc)

      elsif user != nil
        @microposts = Micropost.where(user_id: user).order(likes_count: :desc)

    end

  end

  # GET /microposts/1 or /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])
    @comments = Comment.where(micropost_id: @micropost.id)
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    api_key = request.headers[:HTTP_X_API_KEY]
    @micropost = Micropost.new(micropost_params)

    if current_user != nil
      @micropost.user_id = current_user.id
      @micropost.creator_name = current_user.email
    elsif api_key.nil?
      render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
    else
      @user = User.find_by_api_key(api_key)
      if @user.nil?
        render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
      else
        @micropost.user_id = @user.id
        @micropost.creator_name = @user.email
          unless url_valid?(micropost_params[:url])
            render :json => { "status" => "400", "error" => "No valid URL provided" }, status: :bad_request and return

          end
        end
      end

      respond_to do |format|
        if micropost_params[:url] != "" && Micropost.exists?(url: micropost_params[:url])
          @micropost = Micropost.find_by(url: micropost_params[:url])
          format.html { redirect_to @micropost }
          # CAMBIAR ^ para que redireccione a la vista
          format.json { render json: @micropost, status: :ok }
        end

        if micropost_params[:url] != "" && micropost_params[:text] != ""
          @comment = Comment.new
          @comment.text = @micropost.text
          @comment.micropost = @micropost
          @comment.user = @user
          @micropost.text = ""
          if @micropost.save && @comment.save
            format.html { redirect_to microposts_url(:sort => "date") }
            format.json { render :show, status: :created, location: @micropost }
          end
        end
        if @micropost.save
          format.html { redirect_to microposts_url(:sort => "date") }
          format.json { render :show, status: :created, location: @micropost }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @micropost.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /microposts/1 or /microposts/1.json
    def update
      api_key = request.headers[:HTTP_X_API_KEY]
      if api_key.nil?
        render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
      else
        @user = User.find_by_api_key(api_key)
        if @user.nil?
          render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
        elsif @micropost.user_id != @user.id
          render :json => { "status" => "401", "error" => "Only the creator of the micropost can edit it." }, status: :unauthorized and return
          unless url_valid?(micropost_params[:url])
            render :json => { "status" => "400", "error" => "No valid URL provided" }, status: :bad_request and return
          end
        end
      end
      if @micropost.url != "" && !params[:text].nil?
        render :json => { "status" => "400", "error" => "Cannot fill the text field of a Micropost with URL" }, status: :bad_request and return
      end
      respond_to do |format|
        if @micropost.update(micropost_params)
          format.html { redirect_to micropost_url(@micropost) }
          format.json { render :show, status: :ok, location: @micropost }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @micropost.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /microposts/1 or /microposts/1.json
    def destroy
      api_key = request.headers[:HTTP_X_API_KEY]
      if api_key.nil?
        render :json => { "status" => "401", "error" => "No Api key provided." }, status: :unauthorized and return
      else
        @user = User.find_by_api_key(api_key)
        if @user.nil?
          render :json => { "status" => "401", "error" => "No User found with the Api key provided." }, status: :unauthorized and return
        elsif @micropost.user_id != @user.id
          render :json => { "status" => "401", "error" => "Only the creator of the micropost can delete it." }, status: :unauthorized and return
        end
      end
      @micropost.destroy

      respond_to do |format|
        format.html { redirect_to microposts_url }
        render :json => { "status" => "204", "error" => "Micropost delete successfully" }, status: :ok and return
      end
    end

    def like
      @micropost.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    end

    def unlike
      @micropost.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    end

    def url_valid?(url)
      if url != ""
        url = URI.parse(url) rescue false
      end
      url.kind_of?(URI::HTTP) || url.kind_of?(URI::HTTPS) || url === ""
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      if Micropost.exists?(params[:id])
        @micropost = Micropost.find(params[:id])
      elsif @micropost.nil?
        render :json => { "status" => "404", "error" => "No Micropost with the id provided found." }, status: :not_found
      end
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      if current_user != nil
        params.require(:micropost).permit(:title, :url, :text, :user_id, :creator_name)
      else
        params.permit(:title, :url, :text)
      end
    end

  end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table border="0">
    <tbody>
    <tr>
      <td class=taula_submit>
        <%= form.label :title %>
      </td>
      <td>
        <%= form.text_field :title, :size => 50 %>
      </td>
    </tr>
    <tr>
      <td></td>
    </tr>
    <tr>
      <td class=taula_submit>
        <%= form.label :url %>
      </td>
      <td>
        <%= form.url_field :url, :size => 50 %>
      </td>
    </tr>
    <tr>
      <td class=taula_submit>
        <%= form.label :text %>
      </td>
      <td>
        <%= form.text_area :text, :size => "50x4" %>
      </td>
    </tr>
<!--
    <tr>
      <td class=taula_submit>
        <%= form.label :user_id, style: "display: block" %>
      </td>
      <td>
        <%= form.number_field :user_id %>
      </td>
    </tr>
-->
    <tr>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <%= form.submit "submit" %>
      </td>
    </tr>
    <tr height="20px"></tr>
    <tr>
      <td></td>
      <td class="foot">
        Leave url blank to submit a question for discussion. If there is no url, text will appear at the top of the thread. If there is a url, text is optional.
        <br>
      </td>
    </tbody>
  </table>

<% end %>

app/views/microposts/_micropost.html.erb
<div id="<%= dom_id micropost %>">
  <% if current_user %>
    <% pre_like = micropost.likes.find { |like| like.user_id == current_user.id } %>
    <% if current_user.email == User.search_name(micropost.user_id) %>
      <span class="unable_unvote">*</span>
    <% else %>
      <% if !pre_like %>
        <%= button_to '▲', micropost_likes_path(micropost.id), method: :post, form_class: 'upvoted_button', class: 'upvoted_button_c' %>
      <% else %>
        <span class="non-existent-vote"></span>
      <% end %>
    <% end %>
  <% else %>
    <span class="upvote_comments"><a href="<%= new_user_session_path %>">▲</a></span>
  <% end %>
  <span class="title"><a href="<%= "/microposts/" %><%= micropost.id %>"><%= micropost.title %></a> </span>
  <span class="url_post">
    <%= link_to micropost.url, "#{micropost.url}" %>
  </span>
  <br>
  <div class="post_info">
    <span><%= micropost.likes.count %> <%= (micropost.likes.count) == 1 ? 'point' : 'points' %> by
      <% if current_user %>
        <% if current_user.email == User.search_name(micropost.user_id) %>
          <a class="link_user" href="/users/edit"><%= micropost.user.email %></a>
        <% else %>
          <a class="link_user" href="/users/<%= micropost.user_id %>"><%= micropost.user.email %></a>
        <% end %>
      <% else %>
          <a class="link_user" href="/users/<%= micropost.user.id %>"><%= micropost.user.email %></a>
      <% end %>
    </span>
    <span>
    <% if ((Time.now - micropost.created_at) / 1.year).round >= 1 %>
      <%= ((Time.now - micropost.created_at) / 1.year).round %>  years ago
    <% else %>
      <% if ((Time.now - micropost.created_at) / 1.month).round >= 1 %>
        <%= ((Time.now - micropost.created_at) / 1.month).round %> months ago
      <% else %>
        <% if ((Time.now - micropost.created_at) / 1.week).round >= 1 %>
          <%= ((Time.now - micropost.created_at) / 1.week).round %> weeks ago
        <% else %>
          <% if ((Time.now - micropost.created_at) / 1.day).round >= 1 %>
            <%= ((Time.now - micropost.created_at) / 1.day).round %>  days ago
          <% else %>
            <% if ((Time.now - micropost.created_at) / 1.hour).round >= 1 %>
              <%= ((Time.now - micropost.created_at) / 1.hour).round %> hours ago
            <% else %>
              <% if ((Time.now - micropost.created_at) / 1.minute).round >= 1 %>
                <%= ((Time.now - micropost.created_at) / 1.minute).round %> minutes ago
              <% else %>
                <%= ((Time.now - micropost.created_at) / 1.second).round %> seconds ago
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </span>
    <span class="barres">|</span>
    <span>
    <a href="<%= "/microposts/" %><%= micropost.id %>">
      <% if micropost.comments.count == 0 %>
        <span class=edit_portada> <%= 'discuss' %></span>
      <% else %>
        <span class="edit_portada"> <%= micropost.comments.count %> <%= (micropost.comments.count) == 1 ? 'comment' : 'comments' %></span>
      <% end %>
    </a>
  </span>
    <span>
      <% if current_user %>
        <% if current_user.email == User.search_name(micropost.user_id) %>
          <span class="barres">|</span>
          <a class="edit_portada" href="<%= "/microposts/" %><%= micropost.id %><%= "/edit" %>"><%= "edit" %></a>
        <% end %>
      <% end %>
    </span>
    <span>
      <% if current_user %>
        <% if current_user.email == User.search_name(micropost.user_id) %>
          <span class="barres">|</span>
          <%= button_to 'delete', micropost, method: :delete, form_class: 'delete_button', class: 'delete_portada' %>
        <% end %>
      <% end %>
    </span>
    <span>
    <% if current_user %>
      <% pre_like = micropost.likes.find { |like| like.user_id == current_user.id } %>
        <% if pre_like %>
          |<%= button_to 'unvote', micropost_like_path(micropost.id, pre_like), method: :delete, form_class: 'downvoted_button', class: 'downvoted_button_c' %>
      <% end %>
    <% end %>
  </span>
  </div>
</div>

app/views/microposts/edit.html.erb
<thead>
<table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tr>
    <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=<% microposts_url %>>
              <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="=hname"><%= link_to 'Hacker News', microposts_url, class: 'ruby_link' %></b></span>
            <span class="pagetop_new"><%= link_to 'new', microposts_url(:sort => "date"), class: 'ruby_link' %></span>
            |
            <span class="pagetop"><a href="/users/<%= current_user.id %>/comments"> threads </a> </span>
            | <span class="pagetop"><%= link_to 'submit', new_micropost_url, class: 'ruby_link' %></span>
          </td>
          <td style="text-align:right;padding-right:4px;">
            <%= link_to current_user.email, edit_user_registration_path, class: 'ruby_link' %>
            | <%= link_to 'logout', destroy_user_session_path, class: 'ruby_link', data: { turbo: "false" }, method: :delete %>
          </td>
        </tr>
        </tbody>

      </table>
    </td>
  </tr>
  <tr style="height:10px"></tr>
</table>
</thead>

<table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <tr>
      <td style = "background-color:#f6f6ef; width:85%; align-self: center; padding-right:50px">
      <span class="unable_unvote">*</span>
      <span class="title"><a href="<%= "/microposts/" %><%= @micropost.id %>"><%= @micropost.title %></a> </span>
      <span class="url_post">
          <%= link_to @micropost.url, "#{@micropost.url}" %>
      </span>
      </td>
    </tr>

    <tr>
      <td class="post_info" style = "background-color:#f6f6ef; width:84%; align-content: center; padding-bottom: 20px">
        <span> <%= @micropost.likes.count %> <%= (@micropost.likes.count) == 1 ? 'point' : 'points' %> by</span>
        <span>
          <a class="link_user" href="/users/<%= @micropost.user.id %>"><%= @micropost.user.email %></a>
        </span>
        <span>
            <% if ((Time.now - @micropost.created_at) / 1.year).round >= 1 %>
              <%= ((Time.now - @micropost.created_at) / 1.year).round %>  years ago
            <% else %>
              <% if ((Time.now - @micropost.created_at) / 1.month).round >= 1 %>
                <%= ((Time.now - @micropost.created_at) / 1.month).round %> months ago
              <% else %>
                <% if ((Time.now - @micropost.created_at) / 1.week).round >= 1 %>
                  <%= ((Time.now - @micropost.created_at) / 1.week).round %> weeks ago
                <% else %>
                  <% if ((Time.now - @micropost.created_at) / 1.day).round >= 1 %>
                    <%= ((Time.now - @micropost.created_at) / 1.day).round %>  days ago
                  <% else %>
                    <% if ((Time.now - @micropost.created_at) / 1.hour).round >= 1 %>
                        <%= ((Time.now - @micropost.created_at) / 1.hour).round %> hours ago
                      <% else %>
                      <% if ((Time.now - @micropost.created_at) / 1.minute).round >= 1 %>
                      <%= ((Time.now - @micropost.created_at) / 1.minute).round %> minutes ago
                      <% else %>
                      <%= ((Time.now - @micropost.created_at) / 1.second).round %> seconds ago
                      <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          </span>
        <span>
          | <a class="comments" href="<%="/microposts/"%><%=@micropost.id%>"><%= " comments" %></a>
        <!-- num comments -->
        </span>
      </td>
    </tr>
</tbody>

<tbody class="itemlist">
  <tr height="20px">
    <td class="taula_sencera">
      <%= render "editForm", micropost: @micropost %>
    </td>
  </tr>
</table>
<br>

app/views/microposts/index.html.erb
<p style="color: green"><%= notice %></p>

<thead>
<table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tr>
    <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" >
        <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=<% microposts_url %>>
              <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="=hname"><%= link_to 'Hacker News', microposts_url(:sort =>"likes"), class: 'ruby_link' %></b></span>
            <span class="pagetop_new"><%= link_to 'new', microposts_url(:sort =>"date"), class: 'ruby_link' %></span>
            <% if current_user %>
              <span class="pagetop"><a href="/users/<%= current_user.id %>/comments"> | threads </a> </span>
            <% end %>
            | <span class="pagetop"><%= link_to 'ask', microposts_url(:type =>"ask"), class: 'ruby_link' %></span>
            <% if current_user %>
              | <span class="pagetop"><%= link_to 'submit', new_micropost_url, class: 'ruby_link' %></span>
            <% else %>
              | <span class="pagetop"><%= link_to 'submit', new_user_session_path, class: 'ruby_link' %></span>
            <% end %>
          </td>
          <td style="text-align:right;padding-right:4px;color: black">
            <% if current_user %>
              <%= link_to current_user.email, edit_user_registration_path, class: 'ruby_link' %>
              | <%= link_to 'logout', destroy_user_session_path, class: 'ruby_link', data: {turbo: "false"}, method: :delete %>
            <% else %>
              <%= link_to 'login', new_user_session_path, class: 'ruby_link' %>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  <tr style="height:10px"></tr>
</table>
</thead>
<tbody border="0" cellpadding="0" cellspacing="0" class="itemlist">

<% i = 0 %>
<% @microposts.each do |micropost| %>
  <% i = i + 1 %>
  <table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
    <tr>
      <td class="enum"><span><%= i %>.</span></td>
      <td class="sub">
        <%= render micropost %>
      </td>
    </tr>
    <tr>
      <td>
        <br class="br_between_microposts">
      </td>
    </tr>
    <% if i == @microposts.size %>
      <tr>
        <td>
          <br class="br_peu">
        </td>
        <td>
          <hr class="orange_line">
          <br>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>
<br>

app/views/microposts/show.html.erb
<thead>
<table id="hnmain" border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tr>
    <td bgcolor="#ff6600">
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
        <tr>
          <td style="width:18px;padding-right:4px">
            <a href=<% microposts_url %>>
              <img src="https://news.ycombinator.com/y18.gif" width="18" height="18" style="border:1px white solid;">
            </a>
          </td>
          <td style="line-height:12pt; height:10px;">
            <span class="pagetop"><b class="=hname"><%= link_to 'Hacker News', microposts_url, class: 'ruby_link' %></b></span>
            <span class="pagetop_new"><%= link_to 'new', microposts_url(:sort => "date"), class: 'ruby_link' %></span>
            <% if current_user %>
              <span class="pagetop"><a href="/users/<%= current_user.id %>/comments"> | threads </a> </span>
            <% end %>
            | <span class="pagetop"><%= link_to 'ask', microposts_url(:type => "ask"), class: 'ruby_link' %></span>
            <% if current_user %>
              | <span class="pagetop"><%= link_to 'submit', new_micropost_url, class: 'ruby_link' %></span>
            <% else %>
              | <span class="pagetop"><%= link_to 'submit', new_user_session_path, class: 'ruby_link' %></span>
            <% end %>
          </td>
          <td style="text-align:right;padding-right:4px;">
            <% if current_user %>
              <%= link_to current_user.email, edit_user_registration_path, class: 'ruby_link' %>
              | <%= link_to 'logout', destroy_user_session_path, class: 'ruby_link', data: { turbo: "false" }, method: :delete %>
            <% else %>
              <%= link_to 'login', new_user_session_path, class: 'ruby_link' %>
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  <tr style="height:10px"></tr>
</table>
</thead>

<table border="0" cellpadding="0" align="center" cellspacing="0" width="85%" bgcolor="#f6f6ef">
  <tbody>
    <tr>
      <td style = "background-color:#f6f6ef; width:85%; align-self: center; padding-left: 25px">
        <span class="info_detail_post">
          <% if current_user %>
            <% pre_like = @micropost.likes.find { |like| like.user_id == current_user.id} %>
              <% if current_user.email == User.search_name(@micropost.user_id)%>
              <span class="unable_unvote_detail">*</span>
            <% else %>
              <% if !pre_like %>
                <%= button_to '▲', micropost_likes_path(@micropost.id), method: :post, form_class:'upvoted_button', class: 'upvoted_button_detail_c' %>
              <% else %>
                <span class="non-existent-vote-detail"></span>
              <% end %>
            <% end %>
          <% else %>
            <span class="upvote"><a href="<%= new_user_session_path %>">▲</a></span>
          <% end %>
            <span class="title"><a href="<%= "/microposts/" %><%= @micropost.id %>"><%= @micropost.title %></a> </span>
            <span class="url_post">
                <%= link_to @micropost.url, "#{@micropost.url}" %>
            </span>
        </span>
      </td>
    </tr>

    <tr>
      <td class="post_info_detail" style = "background-color:#f6f6ef; width:84%; align-content: center; padding-left: 25px">
        <span class="author_post">
           <span> <%= @micropost.likes.count %> <%= (@micropost.likes.count) == 1 ? 'point' : 'points' %> by
             <% if current_user %>
               <% if current_user.email == User.search_name(@micropost.user_id)%>
                 <a class="link_user" href="/users/edit"><%= @micropost.user.email %></a>
               <% else %>
                 <a class="link_user" href="/users/<%= @micropost.user_id %>"><%= @micropost.user.email %></a>
               <% end %>
             <% else %>
               <a class="link_user" href="/users/<%= @micropost.user.id %>"><%= @micropost.user.email %></a>
             <% end %>
           </span>
          <span>
            <% if ((Time.now - @micropost.created_at) / 1.year).round >= 1 %>
              <%= ((Time.now - @micropost.created_at) / 1.year).round %>  years ago
            <% else %>
              <% if ((Time.now - @micropost.created_at) / 1.month).round >= 1 %>
                <%= ((Time.now - @micropost.created_at) / 1.month).round %> months ago
              <% else %>
                <% if ((Time.now - @micropost.created_at) / 1.week).round >= 1 %>
                  <%= ((Time.now - @micropost.created_at) / 1.week).round %> weeks ago
                <% else %>
                  <% if ((Time.now - @micropost.created_at) / 1.day).round >= 1 %>
                    <%= ((Time.now - @micropost.created_at) / 1.day).round %>  days ago
                  <% else %>
                    <% if ((Time.now - @micropost.created_at) / 1.hour).round >= 1 %>
                        <%= ((Time.now - @micropost.created_at) / 1.hour).round %> hours ago
                    <% else %>
                      <% if ((Time.now - @micropost.created_at) / 1.minute).round >= 1 %>
                        <%= ((Time.now - @micropost.created_at) / 1.minute).round %> minutes ago
                      <% else %>
                        <%= ((Time.now - @micropost.created_at) / 1.second).round %> seconds ago
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </span>
          <span>
            <% if current_user %>
              <% pre_like = @micropost.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                  |<%= button_to 'unvote', micropost_like_path(@micropost.id, pre_like), method: :delete, form_class:'downvoted_button', class: 'downvoted_button_c' %>
              <% end %>
              <span>
                <% if current_user.email == User.search_name(@micropost.user_id)%>
                  <span class="barres">|</span>
                 <a class="edit" href="<%= "/microposts/" %><%= @micropost.id %><%= "/edit" %>"><%= "edit" %></a>
                <% end %>
              </span>
              <span>
                <a class="comments" href="<%="/microposts/"%><%=@micropost.id%>">
                  <% if @micropost.comments.count == 0 %>
                    <%= ' | discuss' %>
                  <% else %>
                     | <%= @micropost.comments.count %> <%= (@micropost.comments.count) == 1 ? 'comment' : 'comments'%>
                  <% end %>
                </a>
              </span>
            <% end %>
          </span>
        </span>
      </td>
    </tr>
    <tr>
      <td class="post_text" style="padding-left: 25px ">
        <br>
        <%= @micropost.text %>
      </td>
    </tr>
  </tbody>

<tbody class="itemlist">
  <tr>
    <td class="taula_sencera">
      <%= form_for([@micropost, @micropost.comments.build]) do |f| %>
        <p style="padding-left: 25px">
          <%= f.text_area :text, :size => "80x8" %>
        </p>
        <p style="padding-left: 25px">
          <% if current_user %>
            <%= f.submit "add comment"%>
          <% else %>
            <button id="mybutton"><a href="<%= new_user_session_path %>">add comment</a></button>
          <% end %>
        </p>
        <%end%>
    </td>
  </tr>
  <tr style="padding-top: 8px">
    <td>
      <!--
      estoy aqui
      -->
      <%= render @micropost.comments.where(parent_id: nil).includes(:user).order(likes_count: :desc) %>
    </td>
  </tr>
</tbody>
</table>
<br>